Traceback (most recent call last):
  File "launcher.py", line 29, in <module>
    app = qt.QApplication([])
AttributeError: 'module' object has no attribute 'QApplication'
Traceback (most recent call last):
  File "launcher.py", line 29, in <module>
AttributeError: 'module' object has no attribute 'QApplication'
Traceback (most recent call last):
  File "launcher.py", line 30, in <module>
    app = QApplication([])
NameError: name 'QApplication' is not defined
Traceback (most recent call last):
  File "launcher.py", line 8, in <module>
  File "PyQt4\QtGui.pyc", line 12, in <module>
  File "PyQt4\QtGui.pyc", line 10, in __load
ImportError: No module named QtCore
Traceback (most recent call last):
  File "launcher.py", line 8, in <module>
  File "PyQt4\QtGui.pyc", line 12, in <module>
  File "PyQt4\QtGui.pyc", line 10, in __load
ImportError: No module named QtCore
Traceback (most recent call last):
  File "launcher.py", line 8, in <module>
  File "PyQt4\QtGui.pyc", line 12, in <module>
  File "PyQt4\QtGui.pyc", line 10, in __load
ImportError: No module named QtCore
Traceback (most recent call last):
  File "launcher.py", line 39, in <lambda>
  File "launcher.py", line 30, in <lambda>
  File "launcher.py", line 21, in select_dir
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: ''
